### ISSUE TITLE
Bedrock players can't pay other players.

### ISSUE THREAD

**Issue by Im-Really-Sorry** [LemmyWorld/LWMC-Issues#3]
When you pay someone, you are required to click the chat to confirm the payment to someone. In bedrock, you are unable to click the chat to pay someone, thus unable to pay anyone money.

**Comment by SigurdVie** [comment]
I've disabled payment confirmation for the moment. It seems like I need to create a specialized custom command alias via the CMI plugin (https://www.zrips.net/cmi/commands/specialized/). But for now, payments should work on bedrock, and is instant.
